#!/usr/bin/env php
<?php
/**
 * Update the GitHub workflow files for LocalGov Drupal repos.
 */

require_once __DIR__ . '/vendor/autoload.php';

use Dotenv\Dotenv;
use LocalGovDrupal\GithubWorkflowManager\Config;
use LocalGovDrupal\GithubWorkflowManager\WorkflowUpdater;

// Load a GitHub access token.
$dotenv = Dotenv::createImmutable(__DIR__);
$dotenv->load();
$github_access_token = $_ENV['GITHUB_ACCESS_TOKEN'];

// Load config.
$config = new Config();

// Update workflows.
$updater = new WorkflowUpdater($github_access_token, $config);
$updater->run();
